import React, { Component } from 'react';
import CardButton from '../components/cardButton';

class IntroPage extends Component {
  constructor() {
    super();
    this.state = {
      instructions: 'Welcome to our online murder mystery game! In this immersive experience, you\'ll step into the shoes of a detective and work to solve a perplexing murder case. Start by acquainting yourself with the characters and their motives. Select a character to interrogate by typing questions in the text box. Be observant and collect evidence. When you believe you have enough evidence, click the accuse button on the character you believe is guilty.The game will respond – if you\'re right, you\'ll solve the murder and win. ',
      gameIntro: false,
      titlePage: true
    }
  }

  // Handle progressing through the intro
  goToStory = () => {
    this.setState({ 
      titlePage: false,
      gameIntro: false
    });
  };

  goToIntro = () => {
    this.setState({
      titlePage: false,
      gameIntro: true
    })
  }

  render() {
    return (
      <div className="gameIntro">
        <img className='main-notecard' src={this.props.image} alt="background"/>
        {/* <h1>Murder Mystery</h1> */}
        {this.props.story != null ? (
          !this.state.titlePage ? (
            this.state.gameIntro ? (
              <section className="intro">
                {/* Show instructions in list format */}
                <h1>Instructions:</h1>
                <ol className='instructions'>
                  <li><h2>Understand the Premise:</h2>Get acquainted with the game's theme and storyline. You'll be stepping into the role of a detective to solve a murder mystery.</li><br></br>
                  <li><h2>Familiarize Yourself with Characters:</h2>Study the characters involved in the game and their potential motives. Each character holds clues that could aid in solving the mystery.</li><br></br>
                  <li><h2>Choose a Character to Interrogate:</h2>Start by selecting a character to question. Type your inquiries in the text box to gather information and clues. Be strategic in your questioning.</li><br></br>
                  <li><h2>Observe Carefully:</h2>Pay close attention to the details. Look for any inconsistencies, suspicious behavior, or hints dropped by the characters during your interrogation.</li><br></br>
                  <li><h2>Collect Evidence:</h2>As you interact and investigate, gather evidence.</li><br></br>
                  <li><h2>Make Your Accusation:</h2>When you're confident you've gathered sufficient evidence and have a prime suspect in mind, click the "Accuse" button on the character you believe is guilty.</li><br></br>
                  <li><h2>Await the Game's Response:</h2>The game will react to your accusation. If your choice is correct, you'll successfully solve the murder mystery and emerge victorious!</li><br></br>
                </ol>

                <button onClick={this.goToStory}>Continue</button>
              </section>
            ) : (
              <section className="intro">
                <h1>Story:</h1>
                {/* Show story summary */}
                <p className="synopsis">{this.props.story.synopsys}</p>
                <button onClick={this.props.startGame}>Start Game</button>
              </section>
            )
          ):(
            <section className='intro'>
              <h1>GPT Powered Murder Mystery</h1>
              <h2>Welcome to Tyler's murder mystery game. The story, characters and messages are generated by OpenAI. Try to solve the case and have fun!</h2>
              <div className='button'>
                <button onClick={this.goToIntro}>See Instructions</button>
              </div>
              <br></br>
              <div className='button'>
                <button onClick={this.goToStory}>Skip Instructions</button>
              </div>
            </section>
          )
        ) : (
          <p>Loading data</p>
        )}
      </div>
    );
  }
}

export default IntroPage;